modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/devsavage/soulmatter/issues"

[[mods]]
    modId="soulmatter"
    version="${file.jarVersion}"
    displayName="SoulMatter"
    updateJSONURL="https://api.savagedev.io/mc-mods/soulmatter/versions?forge=true"
    displayURL="https://mc.savagedev.io/minecraft-mods/soulmatter/"
    authors="savagedev"
    description='''
    '''
[[dependencies.soulmatter]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="savagecore"
    mandatory=true
    versionRange="[1.15.2-0.0.0,]"
    ordering="BEFORE"
    side="BOTH"