modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/devsavage/soulmatter/issues"
license="MIT"

[[mods]]
    modId="soulmatter"
    version="${mod_version}"
    displayName="SoulMatter"
    updateJSONURL="https://api.savagedev.io/mc-mods/soulmatter/versions?forge=true&version=1.17.1"
    displayURL="https://nlcc.savagedev.io/minecraft-mods/soulmatter/"
    authors="savagedev"
    description='''
    '''
[[dependencies.soulmatter]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="savagecore"
    mandatory=true
    versionRange="[1.20.1-1.0.0.0,)"
    ordering="BEFORE"
    side="BOTH"