modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/devsavage/soulmatter/issues"
license="MIT"

[[mods]]
    modId="soulmatter"
    version="${file.jarVersion}"
    displayName="SoulMatter"
    updateJSONURL="https://api.savagedev.io/mc-mods/soulmatter/versions?forge=true"
    displayURL="https://nlcc.savagedev.io/minecraft-mods/soulmatter/"
    authors="savagedev"
    description='''
    '''
[[dependencies.soulmatter]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17]"
    ordering="NONE"
    side="BOTH"
[[dependencies.soulmatter]]
    modId="savagecore"
    mandatory=true
    versionRange="[1.16.4-2.0.0,]"
    ordering="BEFORE"
    side="BOTH"